version: '3'

services:
  api-twitter:
    build: .
    networks:
      - lucy_rede
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: uvicorn tweets:app --reload --port=8000 --host=0.0.0.0